### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by saleem-hadad** [binarytorch/mysenior#1]
Here are some ideas for future improvement of MySenior:

**Major**

- [ ] Tutor's Calender 

**Minor**

- [ ] Update offer price
- [ ] Support real-time notifications
- [ ] Update tutor/student profile

Feel free to suggest yours as well 📚
Happy Learning ❤️
